### PR TITLE
Added tests for Kylie Sanderson

### PR DESCRIPTION
**Pull request by kyliesanderson**

### CODE REVIEW

**Comment by Quangmire** [comment]
Get your input values between 1 and 1 million inclusive please. The ~400 million line is a bit killer

**Comment by Quangmire** [comment]
Here's a second comment to trigger a second notification. The deadline is in 34 minutes. Please fix your tests. :)

**Comment by kyliesanderson** [comment]
sorry about that! is this better?

**Comment by Quangmire** [comment]
Line 45 has 2 million

**Comment by Quangmire** [comment]
Line 70

**Comment by kyliesanderson** [comment]
done

**Pull request merged**
